<?php include('functions.php');?>
<?php $db_connection = new General;?>

<?php
    if($_POST['func_name'] == 'create_ticket'){
        $sql = "INSERT INTO `lisorubni_kvytky`(`number`, `sosna`, `sosna_dilova`, `jalyna`, `jalyna_dilova`, `dub`, `dub_dilova`, `bereza`, `bereza_dilova`, `vilha`, `vilha_dilova`, `grab`, `grab_dilova`, `jasen`, `jasen_dilova`, `klen`, `klen_dilova`, `osyka`, `osyka_dilova`, `lypa`, `lypa_dilova`, `inshe`, `inshe_dilova`, `chvorost_1c`, `chvorost_2c`, `chvorost_3c`, `total_chvorost`) VALUES (" . $_POST['ticket_number'] . "," . $_POST['sosna'] . "," . $_POST['sosna_dilova'] . "," . $_POST['jalyna'] . "," . $_POST['jalyna_dilova'] . "," . $_POST['dub'] . "," . $_POST['dub_dilova'] . "," . $_POST['bereza'] . "," . $_POST['bereza_dilova'] . "," . $_POST['vilha'] . "," . $_POST['vilha_dilova'] . "," . $_POST['grab'] . "," . $_POST['grab_dilova'] . "," . $_POST['jasen'] . "," . $_POST['jasen_dilova'] . "," . $_POST['klen'] . "," . $_POST['klen_dilova'] . "," . $_POST['osyka'] . "," . $_POST['osyka_dilova'] . "," . $_POST['lypa'] . "," . $_POST['lypa_dilova'] . "," . $_POST['inshe'] . "," . $_POST['inshe_dilova'] . "," . $_POST['chvorost_1c'] . "," . $_POST['chvorost_2c'] . "," . $_POST['chvorost_3c'] . "," . $_POST['total_chvorost'] . ")";
        $sth = $db_connection->dbs->prepare($sql);
        if($sth->execute()){
            echo 'ticket_added';
        }
        echo 'ticket_added';
    } elseif ($_POST['func_name'] == 'add_data') {
        $sql = "INSERT INTO `".$_POST['table_name']."`(`id`, `kvartal`, `vydil`, `ploshcha`, `pidhotovchi_roboty`, `oczystka_lisosiky`, `sosna_a`, `sosna_b`, `sosna_c`, `sosna_d`, `sosna_pv`, `sosna_np`, `jalyna_a`, `jalyna_b`, `jalyna_c`, `jalyna_d`, `jalyna_pv`, `jalyna_np`, `dub_a`, `dub_b`, `dub_c`, `dub_d`, `dub_pv`, `dub_np`, `bereza_a`, `bereza_b`, `bereza_c`, `bereza_d`, `bereza_pv`, `bereza_np`, `vilha_a`, `vilha_b`, `vilha_c`, `vilha_d`, `vilha_pv`, `vilha_np`, `grab_a`, `grab_b`, `grab_c`, `grab_d`, `grab_pv`, `grab_np`, `jasen_a`, `jasen_b`, `jasen_c`, `jasen_d`, `jasen_pv`, `jasen_np`, `klen_a`, `klen_b`, `klen_c`, `klen_d`, `klen_pv`, `klen_np`, `osyka_a`, `osyka_b`, `osyka_c`, `osyka_d`, `osyka_pv`, `osyka_np`, `lypa_a`, `lypa_b`, `lypa_c`, `lypa_d`, `lypa_pv`, `lypa_np`, `inshe_a`, `inshe_b`, `inshe_c`, `inshe_d`, `inshe_pv`, `inshe_np`, `chvorost_1c`, `chvorost_2c`, `chvorost_3c`, `kvytok_number`) VALUES (" . $_POST['row_id'] . "," . $_POST['kvartal'] . "," . $_POST['vydil'] . "," . $_POST['ploshcha'] . "," . $_POST['pidhotovchi_roboty'] . "," . $_POST['oczystka_lisosiky'] . "," . $_POST['sosna_a'] . "," . $_POST['sosna_b'] . "," . $_POST['sosna_c'] . "," . $_POST['sosna_d'] . "," . $_POST['sosna_pv'] . "," . $_POST['sosna_np'] . "," . $_POST['jalyna_a'] . "," . $_POST['jalyna_b'] . "," . $_POST['jalyna_c'] . "," . $_POST['jalyna_d'] . "," . $_POST['jalyna_pv'] . "," . $_POST['jalyna_np'] . "," . $_POST['dub_a'] . "," . $_POST['dub_b'] . "," . $_POST['dub_c'] . "," . $_POST['dub_d'] . "," . $_POST['dub_pv'] . "," . $_POST['dub_np'] . "," . $_POST['bereza_a'] . "," . $_POST['bereza_b'] . "," . $_POST['bereza_c'] . "," . $_POST['bereza_d'] . "," . $_POST['bereza_pv'] . "," . $_POST['bereza_np'] . "," . $_POST['vilha_a'] . "," . $_POST['vilha_b'] . "," . $_POST['vilha_c'] . "," . $_POST['vilha_d'] . "," . $_POST['vilha_pv'] . "," . $_POST['vilha_np'] . "," . $_POST['grab_a'] . "," . $_POST['grab_b'] . "," . $_POST['grab_c'] . "," . $_POST['grab_d'] . "," . $_POST['grab_pv'] . "," . $_POST['grab_np'] . "," . $_POST['jasen_a'] . "," . $_POST['jasen_b'] . "," . $_POST['jasen_c'] . "," . $_POST['jasen_d'] . "," . $_POST['jasen_pv'] . "," . $_POST['jasen_np'] . "," . $_POST['klen_a'] . "," . $_POST['klen_b'] . "," . $_POST['klen_c'] . "," . $_POST['klen_d'] . "," . $_POST['klen_pv'] . "," . $_POST['klen_np'] . "," . $_POST['osyka_a'] . "," . $_POST['osyka_b'] . "," . $_POST['osyka_c'] . "," . $_POST['osyka_d'] . "," . $_POST['osyka_pv'] . "," . $_POST['osyka_np'] . "," . $_POST['lypa_a'] . "," . $_POST['lypa_b'] . "," . $_POST['lypa_c'] . "," . $_POST['lypa_pv'] . "," . $_POST['lypa_np'] . "," . $_POST['inshe_a'] . "," . $_POST['inshe_b'] . "," . $_POST['inshe_c'] . "," . $_POST['inshe_d'] . "," . $_POST['inshe_pv'] . "," . $_POST['inshe_np'] . "," . $_POST['chvorost_1'] . "," . $_POST['chvorost_2'] . "," . $_POST['chvorost_3'] . "," . $_POST['klen_b'] . "," . $_POST['lisorubnyj_kvytok'] . ")";
        $sth = $db_connection->dbs->prepare($sql);
        if($sth->execute()){
            echo 'data_added';
        }
        echo 'data_added';
    }
?>